### ISSUE TITLE
S6a RA: Support for S6a Notify Request/Answer

### ISSUE THREAD

**Issue by richardgood** [RestComm/jain-slee.ss7#11]
Hi

There is a missing declaration in org.mobicents.slee.resource.diameter.s6a.EventIdCacha.java to properly support S6a Notify request/answer messages.

Attached is the diff for this to work properly.

[S6a_NOR_support.txt](https://github.com/RestComm/jain-slee.ss7/files/323215/S6a_NOR_support.txt)

Regards
Richard.

**Comment by vetss** [comment]
Hello @richardgood 

I think you have put your info into a wrong repo.
Please add your info into
https://github.com/RestComm/jain-slee.diameter/issues

It is better if you can provide a pull request for that is missed in our implementing from your point of view.

**Comment by richardgood** [comment]
Apologies didn't see there was a separate repo for jain-slee.diameter.  Will close this issue and re-open to:
https://github.com/RestComm/jain-slee.diameter/issues

**Comment by vetss** [comment]
Hello @richardgood 

> Apologies didn't see there was a separate repo for jain-slee.diameter

No problem. Community feedback is valuavle for us.
